### ISSUE TITLE
Books - page and alignment issues

### ISSUE THREAD

**Issue by austinkocher** [RelevantResearch/penelopeanthias#10]
First of all, I want to say that you are doing an excellent job getting Penelope's information from her faculty page into the new website. It's very impressive. And I like what you've done with the books. A few thoughts about the books.

## Alignment issues
There are some alignment issues on mobile on the homepage and also on the following "Books" page. You probably already saw this, I'm just mentioning it here. If we can find a simple solution, that would be good. It doesn't have to be fancy. 

## Add Books page
Originally, I wanted the "Books" section on the homepage to go to the "Publications" page. But now that I see it this way, I really like it this way. So can we please add a "Books" page in the navigation menu, too? That would be excellent.

![image](https://github.com/user-attachments/assets/6c31fbcd-c32a-448e-9e8f-918c8f21cfef)
![image](https://github.com/user-attachments/assets/6fb1feb8-9b96-4f8e-bcb7-99d6a6f9ac3b)
![image](https://github.com/user-attachments/assets/80c20b06-c3bf-4887-a88d-65931e075ef2)

**Comment by bishal784411** [comment]
Thank you for your kind words! Regarding the alignment issues on mobile, I did notice them and I'm working on a simple solution to ensure everything looks clean and functional without needing anything too complex. As for the 'Books' section, I'm happy to hear that you like the layout. I've already added a 'Books' page to the navigation menu as requested. Let me know if you need any other adjustments!

**Comment by austinkocher** [comment]
I see you have made a page! Great. Can you add it to the navigation menu at the top? I don't see it there yet, but maybe I missed it. Or maybe it hasn't been added to the latest website build.

**Comment by bishal784411** [comment]
The alignment issues on mobile have been resolved. I've made adjustments to both the homepage and the "Books" section. Attached are two screenshots for your reference: one of the homepage and one of the "Books" section, showing the corrected layout.

Please let me know if further adjustments are needed!!

![book section](https://github.com/user-attachments/assets/1c984210-b4ca-48fd-98a3-1e9856897f1d)
![Homepage](https://github.com/user-attachments/assets/db6a9bc9-e725-44e8-a250-f1405bc22559)

**Comment by austinkocher** [comment]
That's great. Naturally, I'll let Riwaj handle this part (and I'll have a look once it's updated on the test website). But I appreciate how quick you are at problem solving.
