### ISSUE TITLE
Remove emojis from page headings

### ISSUE THREAD

**Issue by austinkocher** [RelevantResearch/penelopeanthias#9]
Simple, see attachment.![image](https://github.com/user-attachments/assets/6b76f1df-7480-41fe-a70e-6bc8c9b9a095)

**Comment by bishal784411** [comment]
Initially, I considered removing them from the navigation bar, but after receiving your feedback, I have already made the necessary changes.

**Comment by austinkocher** [comment]
Good work. 🙏
